#!/bin/sh

#bacon /Users/cjng96/iner/sharpenCommander/rust
#find . -name "*.rs" | grep "./src/" | entr -r cargo run
#cargo watch -x "run -- $@"

# cargo install watchexec-cli
watchexec -w src cargo run -- $@



